#!/usr/bin/perl -w

print "# generated by usys.pl - do not edit\n";
print "#include \"syscall.h\"\n";

sub entry {
    my $name = shift;
    my %syscall_num = (
        'MyPrintf'    => 2,
        'gethid'      => 1,
        'task_create' => 3,
        'shm_get'     => 4,
        'P'           => 5,
        'V'           => 6,
        'get_tick'    => 7,
        'fs_create'   => 8,
        'cat'      => 9,
        'fs_remove'   => 10
    );
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, $syscall_num{$name}\n";  # 直接使用数字
    print " ecall\n";
    print " ret\n";
}

entry("MyPrintf");
entry("gethid");
entry("task_create");
entry("shm_get");
entry("P");
entry("V");
entry("get_tick");
entry("fs_create");
entry("cat");
entry("fs_remove");